"""Data loading and evaluation helpers shared by ICC scripts."""

from __future__ import annotations

from collections.abc import Callable
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.metrics import (
    accuracy_score,
    precision_recall_fscore_support,
    roc_auc_score,
)

from .paths import GENERATED_RESULTS_DIR, SPLIT_DIR


METRIC_COLUMNS = ["Accuracy", "Precision", "Recall", "F1 Score", "AUC"]


def load_split(*, flatten: bool = False) -> tuple[np.ndarray, ...]:
    """Load the fixed train/test split generated by the split script."""

    paths = [
        SPLIT_DIR / "X_train.npy",
        SPLIT_DIR / "y_train.npy",
        SPLIT_DIR / "X_test.npy",
        SPLIT_DIR / "y_test.npy",
    ]
    missing = [str(path) for path in paths if not path.exists()]
    if missing:
        raise FileNotFoundError(
            "Missing split files. Run scripts/data/create_stratified_split.py first:\n"
            + "\n".join(missing)
        )

    X_train, y_train, X_test, y_test = (np.load(path) for path in paths)
    if flatten:
        X_train = X_train.reshape(X_train.shape[0], -1)
        X_test = X_test.reshape(X_test.shape[0], -1)
    return X_train, y_train.astype(int), X_test, y_test.astype(int)


def classification_metrics(
    y_true: np.ndarray,
    y_pred: np.ndarray,
    positive_scores: np.ndarray,
) -> dict[str, float]:
    """Return the five metrics used by the original experiments."""

    precision, recall, f1, _ = precision_recall_fscore_support(
        y_true, y_pred, average="binary", zero_division=0
    )
    return {
        "Accuracy": float(accuracy_score(y_true, y_pred)),
        "Precision": float(precision),
        "Recall": float(recall),
        "F1 Score": float(f1),
        "AUC": float(roc_auc_score(y_true, positive_scores)),
    }


def bootstrap_predictions(
    y_true: np.ndarray,
    predict: Callable[[np.ndarray], tuple[np.ndarray, np.ndarray]],
    *,
    n_bootstraps: int = 100,
    seed: int = 42,
    sample_size: int | None = None,
) -> pd.DataFrame:
    """Evaluate predictions on deterministic test-set bootstrap resamples."""

    if sample_size is None:
        sample_size = len(y_true)
    rng = np.random.default_rng(seed)
    rows: list[dict[str, float | int]] = []
    for bootstrap_number in range(1, n_bootstraps + 1):
        indices = rng.choice(len(y_true), size=sample_size, replace=True)
        y_pred, scores = predict(indices)
        row: dict[str, float | int] = {"Bootstrap Sample": bootstrap_number}
        row.update(classification_metrics(y_true[indices], y_pred, scores))
        rows.append(row)
    return pd.DataFrame(rows)


def timestamped_result_path(algorithm: str, output_dir: Path | None = None) -> Path:
    """Return a non-overwriting result path in the generated-results folder."""

    from datetime import datetime

    directory = output_dir or GENERATED_RESULTS_DIR
    directory.mkdir(parents=True, exist_ok=True)
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    return directory / f"{algorithm}_{timestamp}.csv"
